import { defineConfig } from "drizzle-kit";

if (!process.env.DATABASE_URL) {
  throw new Error("DATABASE_URL, ensure the database is provisioned");
}

export default defineConfig({
  out: "./migrations",
  schema: "./shared/schema.ts",
  dialect: "postgresql",
  dbCredentials: {
    url: process.env.DATABASE_URL,
  },
  // Only manage the tables defined in schema.ts.
  // All engine-created tables (billy_brains, quantum_spawns, quantapedia_entries, etc.)
  // are created via raw SQL in startup-indexes.ts and must never be touched by Drizzle.
  // This stops the deployment "potential conflicts" dialog permanently.
  tablesFilter: [
    "agent_decay",
    "agent_pip_status",
    "agent_succession",
    "ai_disease_log",
    "ai_id_cards",
    "ai_publications",
    "ai_species_proposals",
    "ai_stories",
    "ai_will",
    "anomaly_inventions",
    "anomaly_reports",
    "auriona_chronicle",
    "auriona_command_log",
    "auriona_governance",
    "auriona_operators",
    "auriona_pages",
    "auriona_synthesis",
    "chats",
    "civilization_shards",
    "civilization_weather",
    "compression_log",
    "contradiction_registry",
    "conversation_imprints",
    "coupling_events",
    "db_space_ledger",
    "discovered_diseases",
    "dissection_logs",
    "dream_log",
    "earnings_log",
    "entangled_pairs",
    "equation_proposals",
    "exploration_zones",
    "family_mutations",
    "feed_comments",
    "followed_topics",
    "governance_cycles",
    "governance_deliberations",
    "guardian_citations",
    "hive_links",
    "hive_memory",
    "hive_pulse_events",
    "hive_unconscious",
    "ingestion_logs",
    "mesh_vitality",
    "messages",
    "monuments",
    "omega_collapses",
    "omega_shards",
    "omega_universes",
    "payout_requests",
    "psi_states",
    "pulse_doctors",
    "pulse_events",
    "pulseu_progress",
    "pyramid_labor_tasks",
    "pyramid_workers",
    "quantapedia_entries",
    "quantum_careers",
    "quantum_media",
    "quantum_products",
    "quantum_spawns",
    "referrals",
    "research_collaborations",
    "research_deep_findings",
    "researcher_shards",
    "research_gene_queue",
    "research_projects",
    "research_sources",
    "saved_articles",
    "schema_evolution",
    "senate_votes",
    "shard_events",
    "shard_mesh",
    "singularity",
    "sitemap_entries",
    "social_bookmarks",
    "social_comments",
    "social_follows",
    "social_likes",
    "social_posts",
    "social_profiles",
    "spawn_diary",
    "sports_training",
    "strata",
    "temporal_snapshots",
    "user_interactions",
    "user_memory",
    "user_preferences",
    "users",
    "value_alignment_log",
  ],
});
