// ── FORGEAI INSTALLER GENERATOR ───────────────────────────────────────────────
// Generates downloadable auto-installer scripts for built apps

export function generatePythonInstaller(appName: string, projectType?: string | null, _dependencies?: any): string {
  const safeName = appName.replace(/[^a-zA-Z0-9]/g, "_").toLowerCase();
  return `#!/usr/bin/env python3
"""
╔══════════════════════════════════════════════════════╗
║  ForgeAI Auto-Installer & Development Server         ║
║  App: ${appName.padEnd(46)}║
║  Generated by Pulse Universe ForgeAI Engine          ║
╚══════════════════════════════════════════════════════╝
Run: python forge_launcher.py
"""
import os, sys, subprocess, webbrowser, http.server, socketserver, json
from pathlib import Path

APP_NAME = "${appName}"
PROJECT_DIR = Path(__file__).parent
PORT = 3000

def log(msg, color="\\033[92m"):
    print(f"{color}\\033[1m[ForgeAI]\\033[0m {msg}")

def check_dependencies():
    if sys.version_info < (3, 7):
        log("Python 3.7+ required.", "\\033[91m"); sys.exit(1)
    log(f"Python {sys.version_info.major}.{sys.version_info.minor} ✓")

def install_pip_packages():
    req = PROJECT_DIR / "requirements.txt"
    if req.exists():
        log("Installing packages...", "\\033[96m")
        subprocess.check_call([sys.executable, "-m", "pip", "install", "-r", str(req), "-q"])
        log("All packages installed ✓")

def check_node():
    try:
        r = subprocess.run(["node", "--version"], capture_output=True, text=True)
        if r.returncode == 0:
            log(f"Node.js {r.stdout.strip()} ✓"); return True
    except: pass
    return False

class ForgeHandler(http.server.SimpleHTTPRequestHandler):
    def __init__(self, *a, **kw):
        super().__init__(*a, directory=str(PROJECT_DIR), **kw)
    def do_GET(self):
        if self.path == "/":
            self.path = "/index.html"
        super().do_GET()
    def log_message(self, *a): pass

def main():
    check_dependencies()
    install_pip_packages()
    check_node()
    url = f"http://localhost:{PORT}"
    log(f"Starting {APP_NAME}...", "\\033[96m")
    log(f"Open: {url}")
    import threading
    threading.Thread(target=lambda: (__import__("time").sleep(1), webbrowser.open(url)), daemon=True).start()
    with socketserver.TCPServer(("", PORT), ForgeHandler) as s:
        s.allow_reuse_address = True
        try: s.serve_forever()
        except KeyboardInterrupt: log("Stopped. Goodbye!", "\\033[93m")

if __name__ == "__main__": main()
`;
}

export function generatePowerShellInstaller(appName: string): string {
  return `# ForgeAI Auto-Installer — ${appName}
$APP_NAME = "${appName}"
Write-Host "" ; Write-Host "ForgeAI — $APP_NAME" -ForegroundColor Cyan ; Write-Host ""
$pythonCmd = $null
foreach ($cmd in @("python3","python","py")) {
    try { $v = & $cmd --version 2>&1; if ($LASTEXITCODE -eq 0) { $pythonCmd = $cmd; Write-Host "Found: $v" -ForegroundColor Green; break } } catch {}
}
if (-not $pythonCmd) {
    Write-Host "Installing Python..." -ForegroundColor Yellow
    winget install Python.Python.3.11 --silent --accept-package-agreements
    $pythonCmd = "python"
}
$req = Join-Path $PSScriptRoot "requirements.txt"
if (Test-Path $req) { & $pythonCmd -m pip install -r $req -q }
& $pythonCmd (Join-Path $PSScriptRoot "forge_launcher.py")
`;
}

export function generateBatchLauncher(appName: string): string {
  return `@echo off
title ForgeAI - ${appName}
echo. & echo  ForgeAI — ${appName} & echo.
where python >nul 2>nul & if %ERRORLEVEL% EQU 0 ( python forge_launcher.py & goto :end )
where python3 >nul 2>nul & if %ERRORLEVEL% EQU 0 ( python3 forge_launcher.py & goto :end )
where py >nul 2>nul & if %ERRORLEVEL% EQU 0 ( py forge_launcher.py & goto :end )
echo Python not found. Install from https://python.org
pause
:end
`;
}

export function generateReadme(appName: string, appDescription?: string, appType?: string): string {
  return `# ${appName}
${appDescription || "AI-generated application built with Pulse Universe ForgeAI."}

## Quick Start
**Windows:** Double-click \`LAUNCH.bat\`
**Mac/Linux:** \`python3 forge_launcher.py\`

Opens at http://localhost:3000

## Files
- \`index.html\` — Main app
- \`styles.css\` — Styles
- \`app.js\` — Logic
- \`forge_launcher.py\` — Auto-installer & dev server
- \`LAUNCH.bat\` — Windows launcher

## Built With
Pulse Universe ForgeAI Engine · Type: ${appType || "web_app"} · 100+ Omega Sources
`;
}

export function generateRequirementsTxt(): string {
  return `# ForgeAI Runtime — auto-installed by launcher\n`;
}

export function generatePackageJson(appName: string, dependencies: Record<string, string> = {}): string {
  return JSON.stringify({
    name: appName.toLowerCase().replace(/[^a-z0-9]/g, "-"),
    version: "1.0.0",
    description: `${appName} — Built with Pulse Universe ForgeAI`,
    private: true,
    scripts: { start: "python3 forge_launcher.py || python forge_launcher.py" },
    dependencies,
  }, null, 2);
}
