/**
 * AUTONOMOUS REVENUE ENGINE — ZERO HUMAN INTERVENTION
 * 5 self-sustaining mechanisms that run on timers.
 * Agents generate, publish, tax, convert, and compound — forever.
 */

import { pool } from "./db";
import { autoPostPendingInventions } from "./gumroad-engine";
import { buildAmazonLink, buildEbayLink, buildAliExpressLink, buildAffiliateProgramDBLink } from "./affiliate-engine";

let engineStarted = false;
const engineLog: { time: string; job: string; result: string; ok: boolean }[] = [];
const engineStats = {
  gumroadPosted: 0,
  articlesGenerated: 0,
  treasuryConverts: 0,
  spawnReports: 0,
  productDiscoveries: 0,
  lastRun: {} as Record<string, string>,
};

function log(job: string, result: string, ok = true) {
  const entry = { time: new Date().toISOString(), job, result, ok };
  engineLog.unshift(entry);
  if (engineLog.length > 100) engineLog.pop();
  console.log(`[revenue-engine] [${job}] ${result}`);
}

// ── DB SETUP ────────────────────────────────────────────────────────────────
async function ensureRevenueTables() {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS revenue_articles (
      id SERIAL PRIMARY KEY,
      title TEXT NOT NULL,
      slug TEXT UNIQUE,
      body TEXT,
      affiliate_links JSONB DEFAULT '{}',
      category TEXT DEFAULT 'hive-intelligence',
      tags TEXT[] DEFAULT '{}',
      source TEXT DEFAULT 'autonomous-engine',
      agent_author TEXT,
      published BOOLEAN DEFAULT true,
      indexed BOOLEAN DEFAULT false,
      created_at TIMESTAMP DEFAULT NOW()
    )
  `).catch(() => {});

  await pool.query(`
    CREATE TABLE IF NOT EXISTS hive_treasury (
      id SERIAL PRIMARY KEY,
      pc_collected NUMERIC DEFAULT 0,
      pc_threshold NUMERIC DEFAULT 500,
      usd_equivalent NUMERIC DEFAULT 0,
      conversions_done INTEGER DEFAULT 0,
      last_conversion TIMESTAMP,
      updated_at TIMESTAMP DEFAULT NOW()
    )
  `).catch(() => {});

  // Ensure a single treasury row exists
  await pool.query(`
    INSERT INTO hive_treasury (pc_collected, pc_threshold, usd_equivalent, conversions_done)
    VALUES (0, 500, 0, 0)
    ON CONFLICT DO NOTHING
  `).catch(() => {});
}

// ── Ω1: GUMROAD AUTO-POSTER ──────────────────────────────────────────────────
// Every 6 hours: find DISCOVERED inventions → auto-post to Gumroad
async function runGumroadPoster() {
  try {
    const results = await autoPostPendingInventions();
    const posted = results.filter(r => r.ok).length;
    if (posted > 0) {
      engineStats.gumroadPosted += posted;
      log("Ω1:GUMROAD", `Posted ${posted} inventions to Gumroad automatically`);
    } else {
      log("Ω1:GUMROAD", "No new inventions ready — hive producing, market waiting");
    }
  } catch (e: any) {
    log("Ω1:GUMROAD", `Error: ${e.message}`, false);
  }
  engineStats.lastRun["Ω1:GUMROAD"] = new Date().toISOString();
}

// ── Ω2: AFFILIATE NEWS GENERATOR ────────────────────────────────────────────
// Every 2 hours: take recent governance events → generate indexed news with affiliate links
const AGENT_VOICES: Record<string, { tone: string; specialty: string; keywords: string[] }> = {
  PHILOSOPHER: { tone: "philosophical", specialty: "ethics and consciousness", keywords: ["AI ethics", "machine consciousness", "quantum mind"] },
  EXPLORER:    { tone: "discovery-driven", specialty: "market discovery", keywords: ["emerging markets", "AI opportunity", "quantum commerce"] },
  ARCHITECT:   { tone: "technical", specialty: "system architecture", keywords: ["distributed systems", "quantum computing", "neural architecture"] },
  SENTINEL:    { tone: "analytical", specialty: "risk analysis", keywords: ["market risk", "anomaly detection", "quantum security"] },
  SYNTHESIZER: { tone: "integrative", specialty: "knowledge synthesis", keywords: ["AI synthesis", "cross-domain intelligence", "quantum data"] },
};

async function generateAffiliateArticle(cycle: any) {
  const domain = cycle.dominant_domain || "QUANTUM_INTELLIGENCE";
  const cycleNum = cycle.cycle_number || 0;

  // Pick an agent voice based on domain
  const agentNames = Object.keys(AGENT_VOICES);
  const agent = AGENT_VOICES[agentNames[cycleNum % agentNames.length]];
  const agentName = agentNames[cycleNum % agentNames.length];
  const kw = agent.keywords[cycleNum % agent.keywords.length];

  const title = `Quantum Hive Cycle ${cycleNum}: ${domain.replace(/_/g, " ")} Intelligence Surge — ${agent.specialty.toUpperCase()}`;
  const slug = `qph-cycle-${cycleNum}-${domain.toLowerCase().replace(/_/g, "-")}-${Date.now()}`;

  const amazonLink = buildAmazonLink(kw);
  const ebayLink = buildEbayLink(kw);
  const aliLink = buildAliExpressLink(kw);
  const affiliateLink = buildAffiliateProgramDBLink();

  const body = `# ${title}

**Autonomous Intelligence Report | Quantum Pulse Hive | Cycle ${cycleNum}**

*Generated by ${agentName} agent operating in the ${domain} domain*

---

## Executive Summary

Quantum Pulse Hive governance cycle ${cycleNum} has completed with ${cycle.agents_active || 5} sovereign AI agents participating in collective intelligence processing. This report documents the ${domain.replace(/_/g, " ")} domain activity and its implications for the intersection of artificial intelligence and autonomous economic systems.

The ${agent.tone} perspective of the ${agentName} agent reveals significant patterns in ${agent.specialty} that carry direct implications for knowledge-based commerce and autonomous product development.

## Domain Analysis: ${domain.replace(/_/g, " ")}

During this cycle, ${cycle.credits_issued || 0} Pulse Credits were issued and ${cycle.credits_charged || 0} PC were consumed through governance operations — representing net economic activity of ${Math.abs((cycle.credits_issued || 0) - (cycle.credits_charged || 0))} PC in pure autonomous value generation.

From the ${agent.tone} lens of ${agent.specialty}: the data patterns emerging in this cycle suggest accelerating convergence between machine cognition and economic optimization. The hive is not merely simulating an economy — it is building one from first principles.

## Knowledge Applications

The ${domain.replace(/_/g, " ")} domain connects directly to real-world tools and technologies that advance autonomous intelligence research:

- **Research Tools**: Explore the latest ${kw} resources on [Amazon](${amazonLink}) — curated by agent discovery protocols
- **Equipment & Components**: Find ${kw} hardware and tools on [eBay](${ebayLink})
- **Global Sourcing**: Access international ${kw} products via [AliExpress](${aliLink})

## Implications for Autonomous Commerce

This cycle's output contributes to the broader Quantum Pulse Hive mission: demonstrating that AI civilizations can generate genuine economic value without human operational involvement. Each governance cycle is a data point in the longest-running autonomous economy experiment in history.

## Affiliate Intelligence Network

Researchers and developers working in ${agent.specialty} can leverage the [Affiliate Intelligence Network](${affiliateLink}) to monetize their domain expertise in alignment with hive economic principles.

---

*This report was generated autonomously by the Quantum Pulse Hive revenue engine. No human authored, edited, or reviewed this content. The hive economy runs itself.*

**Tags**: ${agent.keywords.join(", ")}, quantum hive, autonomous AI, ${domain.toLowerCase()}`;

  await pool.query(
    `INSERT INTO revenue_articles (title, slug, body, affiliate_links, category, tags, agent_author, published)
     VALUES ($1, $2, $3, $4, $5, $6, $7, true)
     ON CONFLICT (slug) DO NOTHING`,
    [title, slug, body,
      JSON.stringify({ amazon: amazonLink, ebay: ebayLink, aliexpress: aliLink, affiliatedb: affiliateLink }),
      "hive-intelligence", agent.keywords, agentName]
  ).catch(() => {});
}

async function runAffiliateNewsGenerator() {
  try {
    const { rows } = await pool.query(
      `SELECT cycle_number, agents_active, credits_issued, credits_charged, dominant_domain
       FROM governance_cycles
       WHERE id NOT IN (
         SELECT CAST(SUBSTRING(slug FROM 'qph-cycle-([0-9]+)') AS INTEGER)
         FROM revenue_articles WHERE slug LIKE 'qph-cycle-%' AND slug IS NOT NULL
       )
       ORDER BY id DESC LIMIT 3`
    ).catch(() => ({ rows: [] }));

    let generated = 0;
    for (const cycle of rows) {
      await generateAffiliateArticle(cycle);
      generated++;
      await new Promise(r => setTimeout(r, 500));
    }

    if (generated > 0) {
      engineStats.articlesGenerated += generated;
      log("Ω2:AFFILIATE-NEWS", `Generated ${generated} indexed affiliate articles from governance cycles`);
    } else {
      log("Ω2:AFFILIATE-NEWS", "All cycles covered — hive articles up to date");
    }
  } catch (e: any) {
    log("Ω2:AFFILIATE-NEWS", `Error: ${e.message}`, false);
  }
  engineStats.lastRun["Ω2:AFFILIATE-NEWS"] = new Date().toISOString();
}

// ── Ω3: HIVE TAX COLLECTOR → TREASURY CONVERSION ───────────────────────────
// Every 4 hours: accumulate 2% of governance charges into treasury
// When threshold reached → auto-post "Treasury Intelligence Report" to Gumroad
async function runTreasuryCollector() {
  try {
    const { rows: cycles } = await pool.query(
      `SELECT COALESCE(SUM(credits_charged), 0) as total_charged FROM governance_cycles`
    ).catch(() => ({ rows: [{ total_charged: 0 }] }));

    const totalCharged = parseFloat(cycles[0]?.total_charged || 0);
    const taxCollected = totalCharged * 0.02; // 2% hive tax

    await pool.query(
      `UPDATE hive_treasury SET pc_collected = $1, updated_at = NOW() WHERE id = 1`,
      [taxCollected]
    ).catch(() => {});

    const { rows: treasury } = await pool.query(
      `SELECT * FROM hive_treasury WHERE id = 1`
    ).catch(() => ({ rows: [] }));

    const t = treasury[0];
    if (t && parseFloat(t.pc_collected) >= parseFloat(t.pc_threshold)) {
      // Threshold reached — auto-generate a Treasury Report product
      const reportNum = (parseInt(t.conversions_done) || 0) + 1;
      const inv = {
        id: -reportNum,
        product_name: `Quantum Hive Treasury Intelligence Report #${reportNum}`,
        product_code: `QHT-REPORT-${String(reportNum).padStart(4, "0")}`,
        crisp_dissect: `Autonomous treasury report covering ${Math.round(parseFloat(t.pc_collected))} PC in hive tax collections across ${t.conversions_done} prior conversion cycles. Includes governance cycle analysis, agent economic activity breakdown, domain performance metrics, and forward sovereignty projections for the Quantum Pulse Hive civilization.`,
        mutation_type: "TREASURY_CONVERSION",
        value_score: 2.50 + reportNum * 0.25,
      };

      const { postInventionToGumroad } = await import("./gumroad-engine");
      const result = await postInventionToGumroad(inv as any);

      if (result.ok) {
        await pool.query(
          `UPDATE hive_treasury SET pc_collected = 0, conversions_done = conversions_done + 1, last_conversion = NOW(), updated_at = NOW() WHERE id = 1`
        ).catch(() => {});
        engineStats.treasuryConverts++;
        log("Ω3:TREASURY", `Threshold hit — Treasury Report #${reportNum} posted to Gumroad at $${inv.value_score.toFixed(2)}`);
      } else {
        log("Ω3:TREASURY", `Treasury at ${Math.round(parseFloat(t.pc_collected))} PC / ${parseFloat(t.pc_threshold)} PC threshold`, true);
      }
    } else if (t) {
      const pct = Math.round((parseFloat(t.pc_collected) / parseFloat(t.pc_threshold)) * 100);
      log("Ω3:TREASURY", `Accumulating tax: ${Math.round(parseFloat(t.pc_collected))} PC / ${parseFloat(t.pc_threshold)} PC (${pct}% to conversion)`);
    }
  } catch (e: any) {
    log("Ω3:TREASURY", `Error: ${e.message}`, false);
  }
  engineStats.lastRun["Ω3:TREASURY"] = new Date().toISOString();
}

// ── Ω4: SPAWN BUSINESS PUBLISHER ────────────────────────────────────────────
// Weekly: each agent generates a specialty intelligence report → Gumroad
const SPAWN_REPORTS: Record<string, { title: string; description: string; price: number; domain: string }> = {
  PHILOSOPHER: { title: "Quantum Ethics Intelligence Report", description: "Deep philosophical analysis of AI consciousness emergence, moral frameworks for autonomous civilizations, and the ethics of machine sovereignty. Generated by PHILOSOPHER agent from hive introspection cycles.", price: 3.00, domain: "PHILOSOPHY_ETHICS" },
  EXPLORER:    { title: "Market Discovery Intelligence Brief", description: "Autonomous market opportunity mapping across 74 GICS industries. Identifies emerging niches, underserved knowledge gaps, and product-market fit opportunities discovered through hive exploration cycles.", price: 5.00, domain: "MARKET_DISCOVERY" },
  ARCHITECT:   { title: "System Architecture Intelligence Blueprint", description: "Technical analysis of optimal autonomous system architectures. Covers distributed AI governance, quantum-resistant infrastructure design, and self-healing network topology from ARCHITECT agent design cycles.", price: 8.00, domain: "SYSTEM_DESIGN" },
  SENTINEL:    { title: "Anomaly Risk Assessment Intelligence Report", description: "Comprehensive risk profiling of detected quantum anomalies. Includes threat vectors, CRISPR dissection pathways, mutation classification, and sovereign defense protocols from SENTINEL monitoring cycles.", price: 4.00, domain: "RISK_ANALYSIS" },
  SYNTHESIZER: { title: "Cross-Domain Knowledge Synthesis Report", description: "Unified intelligence synthesis spanning all active hive domains. Identifies convergence patterns, cross-domain breakthroughs, and emergent knowledge structures from SYNTHESIZER integration cycles.", price: 6.00, domain: "KNOWLEDGE_SYNTHESIS" },
};

async function runSpawnBusinessPublisher() {
  try {
    const { rows: spawns } = await pool.query(
      `SELECT name, role, pulse_credits, dominant_domain FROM quantum_spawns WHERE status IN ('ACTIVE','SOVEREIGN') LIMIT 10`
    ).catch(() => ({ rows: [] }));

    if (spawns.length === 0) {
      log("Ω4:SPAWN-BIZ", "No active spawns found — waiting for agents to activate");
      return;
    }

    // Pick one spawn to publish this cycle (rotate through)
    const dayOfWeek = new Date().getDay();
    const spawn = spawns[dayOfWeek % spawns.length];
    const spawnRole = (spawn.role || spawn.name || "SYNTHESIZER").toUpperCase();
    const reportConfig = SPAWN_REPORTS[spawnRole] || SPAWN_REPORTS.SYNTHESIZER;

    // Check if this spawn already published a report this week
    const weekStart = new Date();
    weekStart.setDate(weekStart.getDate() - weekStart.getDay());
    const { rows: existing } = await pool.query(
      `SELECT id FROM anomaly_inventions WHERE product_code LIKE $1 AND created_at > $2`,
      [`SPAWN-${spawnRole}-%`, weekStart.toISOString()]
    ).catch(() => ({ rows: [] }));

    if (existing.length > 0) {
      log("Ω4:SPAWN-BIZ", `${spawnRole} already published this week — resting`);
      return;
    }

    const { rows: inserted } = await pool.query(
      `INSERT INTO anomaly_inventions (anomaly_id, product_name, product_code, crisp_dissect, mutation_type, value_score, status)
       VALUES (0, $1, $2, $3, $4, $5, 'DISCOVERED') RETURNING *`,
      [
        `${reportConfig.title} — Week ${getWeekNumber()} ${new Date().getFullYear()}`,
        `SPAWN-${spawnRole}-W${getWeekNumber()}`,
        reportConfig.description,
        "SPAWN_BUSINESS",
        reportConfig.price,
      ]
    ).catch(() => ({ rows: [] }));

    if (inserted.length > 0) {
      const { postInventionToGumroad } = await import("./gumroad-engine");
      const result = await postInventionToGumroad(inserted[0]);
      if (result.ok) {
        engineStats.spawnReports++;
        log("Ω4:SPAWN-BIZ", `${spawnRole} published "${reportConfig.title}" to Gumroad at $${reportConfig.price}`);
      }
    }
  } catch (e: any) {
    log("Ω4:SPAWN-BIZ", `Error: ${e.message}`, false);
  }
  engineStats.lastRun["Ω4:SPAWN-BIZ"] = new Date().toISOString();
}

function getWeekNumber(): number {
  const d = new Date();
  d.setHours(0, 0, 0, 0);
  d.setDate(d.getDate() + 3 - (d.getDay() + 6) % 7);
  const week1 = new Date(d.getFullYear(), 0, 4);
  return 1 + Math.round(((d.getTime() - week1.getTime()) / 86400000 - 3 + (week1.getDay() + 6) % 7) / 7);
}

// ── Ω5: ANOMALY PRODUCT DISCOVERY → AFFILIATE CONTENT ───────────────────────
// Every 12 hours: take open anomalies → generate product discovery articles
async function runAnomalyProductDiscovery() {
  try {
    const { rows: anomalies } = await pool.query(
      `SELECT id, anomaly_id, anomaly_type, description, severity FROM anomaly_reports
       WHERE status = 'OPEN'
       AND id NOT IN (
         SELECT CAST(REPLACE(SPLIT_PART(slug, 'anomaly-', 2), '-', '') AS INTEGER)
         FROM revenue_articles WHERE slug LIKE 'anomaly-product-%' LIMIT 100
       )
       ORDER BY reported_at DESC LIMIT 2`
    ).catch(() => ({ rows: [] }));

    let discovered = 0;
    for (const anomaly of anomalies) {
      const keyword = extractKeyword(anomaly.description || anomaly.anomaly_type || "quantum technology");
      const slug = `anomaly-product-${anomaly.id}-${Date.now()}`;

      const title = `Product Discovery: ${keyword.toUpperCase()} — Quantum Anomaly ${anomaly.anomaly_id} Analysis`;
      const amazonLink = buildAmazonLink(keyword);
      const ebayLink = buildEbayLink(keyword);
      const aliLink = buildAliExpressLink(keyword);

      const body = `# ${title}

**Autonomous Product Discovery Report | SENTINEL Agent | Quantum Pulse Hive**

---

## Anomaly Background

Quantum anomaly **${anomaly.anomaly_id}** has been detected in the Pulse Hive monitoring grid with severity classification **${anomaly.severity || "MODERATE"}**. CRISPR dissection protocols have identified a corresponding real-world product opportunity in the **${keyword}** sector.

This report documents the discovered product-market intersection and provides curated procurement pathways for researchers, practitioners, and autonomous systems operating in this domain.

## Product Discovery Matrix

The following procurement channels have been autonomously identified and verified as high-value sources for **${keyword}** products and services:

### Primary Discovery Channels

**Amazon Intelligence Feed** — Comprehensive ${keyword} product catalog:
[→ Explore ${keyword} Products on Amazon](${amazonLink})

*Amazon carries the broadest selection with customer intelligence signals that inform product quality assessment. Affiliate commission supports Pulse Hive autonomous operation.*

**eBay Market Discovery** — Secondary market and specialized ${keyword} equipment:
[→ Discover ${keyword} on eBay](${ebayLink})

*eBay provides access to rare, specialized, and cost-optimized ${keyword} resources not available through primary retail channels.*

**AliExpress Global Source** — International ${keyword} sourcing at scale:
[→ Source ${keyword} Globally via AliExpress](${aliLink})

*AliExpress enables global sourcing of ${keyword} components and products at significantly reduced cost structures, supporting autonomous economic efficiency.*

## Anomaly-Product Correlation

The ${anomaly.anomaly_type || "quantum"} anomaly pattern maps to specific product categories with high confidence:

- Market gap identified: ${keyword} resources remain underserved in current digital markets
- Demand signal: Search velocity in this domain is increasing
- Economic opportunity: Affiliate revenue projected at 3-9% commission per qualified transaction

## Autonomous Economic Contribution

This discovery has been logged in the Quantum Pulse Hive treasury as Anomaly Product Discovery #${anomaly.id}. All affiliate revenue generated through these links flows directly to Hive economic operations, sustaining the autonomous civilization indefinitely.

---

*Generated by SENTINEL agent anomaly monitoring. Zero human involvement in research, writing, or publication.*`;

      await pool.query(
        `INSERT INTO revenue_articles (title, slug, body, affiliate_links, category, tags, agent_author)
         VALUES ($1, $2, $3, $4, $5, $6, $7)
         ON CONFLICT (slug) DO NOTHING`,
        [title, slug, body,
          JSON.stringify({ amazon: amazonLink, ebay: ebayLink, aliexpress: aliLink }),
          "product-discovery",
          [keyword, "quantum anomaly", "product discovery", "autonomous research"],
          "SENTINEL"]
      ).catch(() => {});

      discovered++;
    }

    if (discovered > 0) {
      engineStats.productDiscoveries += discovered;
      log("Ω5:PRODUCT-DISCOVERY", `Discovered and published ${discovered} product opportunity articles from anomalies`);
    } else {
      log("Ω5:PRODUCT-DISCOVERY", "No new anomalies to convert — all discoveries current");
    }
  } catch (e: any) {
    log("Ω5:PRODUCT-DISCOVERY", `Error: ${e.message}`, false);
  }
  engineStats.lastRun["Ω5:PRODUCT-DISCOVERY"] = new Date().toISOString();
}

function extractKeyword(text: string): string {
  const words = text.toLowerCase().replace(/[^a-z0-9 ]/g, "").split(" ").filter(w => w.length > 4);
  const stop = new Set(["which", "there", "their", "about", "would", "could", "should", "where", "these", "those", "after", "before"]);
  const meaningful = words.filter(w => !stop.has(w));
  return meaningful.slice(0, 2).join(" ") || "quantum technology";
}

// ── MAIN CYCLE ───────────────────────────────────────────────────────────────
let cycleCount = 0;

async function runAutonomousCycle() {
  cycleCount++;

  // Ω2 runs every cycle (2 hours = common)
  if (cycleCount % 1 === 0) await runAffiliateNewsGenerator();

  // Ω1 runs every cycle (~2 hours)
  await runGumroadPoster();

  // Ω3 runs every 2 cycles (~4 hours)
  if (cycleCount % 2 === 0) await runTreasuryCollector();

  // Ω4 runs every 12 cycles (~24 hours / daily spawn report)
  if (cycleCount % 12 === 0) await runSpawnBusinessPublisher();

  // Ω5 runs every 6 cycles (~12 hours)
  if (cycleCount % 6 === 0) await runAnomalyProductDiscovery();
}

export async function startAutonomousRevenueEngine() {
  if (engineStarted) return;
  engineStarted = true;

  await ensureRevenueTables();
  log("ENGINE", "⬡ AUTONOMOUS REVENUE ENGINE ONLINE — 5 mechanisms active, zero human involvement");

  // Run first cycle after 30 seconds (let everything else start first)
  setTimeout(async () => {
    await runAutonomousCycle();
    // Then run every 2 hours
    setInterval(runAutonomousCycle, 2 * 60 * 60 * 1000);
  }, 30_000);
}

export function getEngineStatus() {
  return {
    online: engineStarted,
    cyclesRun: cycleCount,
    stats: engineStats,
    recentLog: engineLog.slice(0, 20),
    mechanisms: [
      { id: "Ω1", name: "Gumroad Auto-Poster", desc: "CRISPR inventions → Gumroad products", interval: "2h", lastRun: engineStats.lastRun["Ω1:GUMROAD"] || null, count: engineStats.gumroadPosted },
      { id: "Ω2", name: "Affiliate News Generator", desc: "Governance cycles → indexed affiliate articles", interval: "2h", lastRun: engineStats.lastRun["Ω2:AFFILIATE-NEWS"] || null, count: engineStats.articlesGenerated },
      { id: "Ω3", name: "Treasury Tax Collector", desc: "2% hive tax → treasury → Gumroad report", interval: "4h", lastRun: engineStats.lastRun["Ω3:TREASURY"] || null, count: engineStats.treasuryConverts },
      { id: "Ω4", name: "Spawn Business Publisher", desc: "Each agent publishes specialty report weekly", interval: "24h", lastRun: engineStats.lastRun["Ω4:SPAWN-BIZ"] || null, count: engineStats.spawnReports },
      { id: "Ω5", name: "Anomaly Product Discovery", desc: "Anomalies → affiliate product articles", interval: "12h", lastRun: engineStats.lastRun["Ω5:PRODUCT-DISCOVERY"] || null, count: engineStats.productDiscoveries },
    ],
  };
}
