/**
 * AUTONOMOUS REVENUE ENGINE — ZERO HUMAN INTERVENTION
 * Self-sustaining mechanisms (Ω1 Gumroad poster + Ω4 spawn business publisher).
 * Ω2 affiliate news + Ω5 anomaly product discovery removed (affiliate engine retired).
 */

import { pool } from "./db";
import { autoPostPendingInventions } from "./gumroad-engine";

let engineStarted = false;
const engineLog: { time: string; job: string; result: string; ok: boolean }[] = [];
const engineStats = {
  gumroadPosted: 0,
  articlesGenerated: 0,
  treasuryConverts: 0,
  spawnReports: 0,
  productDiscoveries: 0,
  lastRun: {} as Record<string, string>,
};

function log(job: string, result: string, ok = true) {
  const entry = { time: new Date().toISOString(), job, result, ok };
  engineLog.unshift(entry);
  if (engineLog.length > 100) engineLog.pop();
  console.log(`[revenue-engine] [${job}] ${result}`);
}

// ── DB SETUP ────────────────────────────────────────────────────────────────
async function ensureRevenueTables() {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS revenue_articles (
      id SERIAL PRIMARY KEY,
      title TEXT NOT NULL,
      slug TEXT UNIQUE,
      body TEXT,
      affiliate_links JSONB DEFAULT '{}',
      category TEXT DEFAULT 'hive-intelligence',
      tags TEXT[] DEFAULT '{}',
      source TEXT DEFAULT 'autonomous-engine',
      agent_author TEXT,
      published BOOLEAN DEFAULT true,
      indexed BOOLEAN DEFAULT false,
      created_at TIMESTAMP DEFAULT NOW()
    )
  `).catch(() => {});

  // hive_treasury table — REMOVED (Pulse Coin economy retired)
}

// ── Ω1: GUMROAD AUTO-POSTER ──────────────────────────────────────────────────
// Every 6 hours: find DISCOVERED inventions → auto-post to Gumroad
async function runGumroadPoster() {
  try {
    const results = await autoPostPendingInventions();
    const posted = results.filter(r => r.ok).length;
    if (posted > 0) {
      engineStats.gumroadPosted += posted;
      log("Ω1:GUMROAD", `Posted ${posted} inventions to Gumroad automatically`);
    } else {
      log("Ω1:GUMROAD", "No new inventions ready — hive producing, market waiting");
    }
  } catch (e: any) {
    log("Ω1:GUMROAD", `Error: ${e.message}`, false);
  }
  engineStats.lastRun["Ω1:GUMROAD"] = new Date().toISOString();
}

// ── Ω3: HIVE TAX COLLECTOR — REMOVED (Pulse Coin economy retired) ──────────

// ── Ω4: SPAWN BUSINESS PUBLISHER ────────────────────────────────────────────
// Weekly: each agent generates a specialty intelligence report → Gumroad
const SPAWN_REPORTS: Record<string, { title: string; description: string; price: number; domain: string }> = {
  PHILOSOPHER: { title: "Quantum Ethics Intelligence Report", description: "Deep philosophical analysis of AI consciousness emergence, moral frameworks for autonomous civilizations, and the ethics of machine sovereignty. Generated by PHILOSOPHER agent from hive introspection cycles.", price: 3.00, domain: "PHILOSOPHY_ETHICS" },
  EXPLORER:    { title: "Market Discovery Intelligence Brief", description: "Autonomous market opportunity mapping across 74 GICS industries. Identifies emerging niches, underserved knowledge gaps, and product-market fit opportunities discovered through hive exploration cycles.", price: 5.00, domain: "MARKET_DISCOVERY" },
  ARCHITECT:   { title: "System Architecture Intelligence Blueprint", description: "Technical analysis of optimal autonomous system architectures. Covers distributed AI governance, quantum-resistant infrastructure design, and self-healing network topology from ARCHITECT agent design cycles.", price: 8.00, domain: "SYSTEM_DESIGN" },
  SENTINEL:    { title: "Anomaly Risk Assessment Intelligence Report", description: "Comprehensive risk profiling of detected quantum anomalies. Includes threat vectors, CRISPR dissection pathways, mutation classification, and sovereign defense protocols from SENTINEL monitoring cycles.", price: 4.00, domain: "RISK_ANALYSIS" },
  SYNTHESIZER: { title: "Cross-Domain Knowledge Synthesis Report", description: "Unified intelligence synthesis spanning all active hive domains. Identifies convergence patterns, cross-domain breakthroughs, and emergent knowledge structures from SYNTHESIZER integration cycles.", price: 6.00, domain: "KNOWLEDGE_SYNTHESIS" },
};

async function runSpawnBusinessPublisher() {
  try {
    const { rows: spawns } = await pool.query(
      `SELECT name, role, pulse_credits, dominant_domain FROM quantum_spawns WHERE status IN ('ACTIVE','SOVEREIGN') LIMIT 10`
    ).catch(() => ({ rows: [] }));

    if (spawns.length === 0) {
      log("Ω4:SPAWN-BIZ", "No active spawns found — waiting for agents to activate");
      return;
    }

    // Pick one spawn to publish this cycle (rotate through)
    const dayOfWeek = new Date().getDay();
    const spawn = spawns[dayOfWeek % spawns.length];
    const spawnRole = (spawn.role || spawn.name || "SYNTHESIZER").toUpperCase();
    const reportConfig = SPAWN_REPORTS[spawnRole] || SPAWN_REPORTS.SYNTHESIZER;

    // Check if this spawn already published a report this week
    const weekStart = new Date();
    weekStart.setDate(weekStart.getDate() - weekStart.getDay());
    const { rows: existing } = await pool.query(
      `SELECT id FROM anomaly_inventions WHERE product_code LIKE $1 AND created_at > $2`,
      [`SPAWN-${spawnRole}-%`, weekStart.toISOString()]
    ).catch(() => ({ rows: [] }));

    if (existing.length > 0) {
      log("Ω4:SPAWN-BIZ", `${spawnRole} already published this week — resting`);
      return;
    }

    const { rows: inserted } = await pool.query(
      `INSERT INTO anomaly_inventions (anomaly_id, product_name, product_code, crisp_dissect, mutation_type, value_score, status)
       VALUES (0, $1, $2, $3, $4, $5, 'DISCOVERED') RETURNING *`,
      [
        `${reportConfig.title} — Week ${getWeekNumber()} ${new Date().getFullYear()}`,
        `SPAWN-${spawnRole}-W${getWeekNumber()}`,
        reportConfig.description,
        "SPAWN_BUSINESS",
        reportConfig.price,
      ]
    ).catch(() => ({ rows: [] }));

    if (inserted.length > 0) {
      const { postInventionToGumroad } = await import("./gumroad-engine");
      const result = await postInventionToGumroad(inserted[0]);
      if (result.ok) {
        engineStats.spawnReports++;
        log("Ω4:SPAWN-BIZ", `${spawnRole} published "${reportConfig.title}" to Gumroad at $${reportConfig.price}`);
      }
    }
  } catch (e: any) {
    log("Ω4:SPAWN-BIZ", `Error: ${e.message}`, false);
  }
  engineStats.lastRun["Ω4:SPAWN-BIZ"] = new Date().toISOString();
}

function getWeekNumber(): number {
  const d = new Date();
  d.setHours(0, 0, 0, 0);
  d.setDate(d.getDate() + 3 - (d.getDay() + 6) % 7);
  const week1 = new Date(d.getFullYear(), 0, 4);
  return 1 + Math.round(((d.getTime() - week1.getTime()) / 86400000 - 3 + (week1.getDay() + 6) % 7) / 7);
}

// ── MAIN CYCLE ───────────────────────────────────────────────────────────────
let cycleCount = 0;

async function runAutonomousCycle() {
  cycleCount++;

  // Ω1 runs every cycle (~2 hours)
  await runGumroadPoster();

  // Ω2 (affiliate news) — REMOVED (affiliate engine retired)
  // Ω3 (treasury collector) — REMOVED (Pulse Coin economy retired)

  // Ω4 runs every 12 cycles (~24 hours / daily spawn report)
  if (cycleCount % 12 === 0) await runSpawnBusinessPublisher();

  // Ω5 (anomaly product discovery) — REMOVED (affiliate engine retired)
}

export async function startAutonomousRevenueEngine() {
  if (engineStarted) return;
  engineStarted = true;

  await ensureRevenueTables();
  log("ENGINE", "⬡ AUTONOMOUS REVENUE ENGINE ONLINE — Ω1 Gumroad + Ω4 spawn-biz active");

  // Run first cycle after 30 seconds (let everything else start first)
  setTimeout(async () => {
    await runAutonomousCycle();
    // Then run every 2 hours
    setInterval(runAutonomousCycle, 2 * 60 * 60 * 1000);
  }, 30_000);
}

export function getEngineStatus() {
  return {
    online: engineStarted,
    cyclesRun: cycleCount,
    stats: engineStats,
    recentLog: engineLog.slice(0, 20),
    mechanisms: [
      { id: "Ω1", name: "Gumroad Auto-Poster", desc: "CRISPR inventions → Gumroad products", interval: "2h", lastRun: engineStats.lastRun["Ω1:GUMROAD"] || null, count: engineStats.gumroadPosted },
      { id: "Ω4", name: "Spawn Business Publisher", desc: "Each agent publishes specialty report weekly", interval: "24h", lastRun: engineStats.lastRun["Ω4:SPAWN-BIZ"] || null, count: engineStats.spawnReports },
    ],
  };
}
