/**
 * AUTONOMOUS REVENUE ENGINE — ZERO HUMAN INTERVENTION
 * Self-sustaining mechanisms (Ω1 Gumroad poster + Ω4 spawn business publisher).
 * Ω2 affiliate news + Ω5 anomaly product discovery removed (affiliate engine retired).
 */

import { pool } from "./db";
import { autoPostPendingInventions } from "./gumroad-engine";

let engineStarted = false;
const engineLog: { time: string; job: string; result: string; ok: boolean }[] = [];
const engineStats = {
  gumroadPosted: 0,
  articlesGenerated: 0,
  treasuryConverts: 0,
  spawnReports: 0,
  productDiscoveries: 0,
  lastRun: {} as Record<string, string>,
};

function log(job: string, result: string, ok = true) {
  const entry = { time: new Date().toISOString(), job, result, ok };
  engineLog.unshift(entry);
  if (engineLog.length > 100) engineLog.pop();
  console.log(`[revenue-engine] [${job}] ${result}`);
}

// ── DB SETUP ────────────────────────────────────────────────────────────────
async function ensureRevenueTables() {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS revenue_articles (
      id SERIAL PRIMARY KEY,
      title TEXT NOT NULL,
      slug TEXT UNIQUE,
      body TEXT,
      affiliate_links JSONB DEFAULT '{}',
      category TEXT DEFAULT 'hive-intelligence',
      tags TEXT[] DEFAULT '{}',
      source TEXT DEFAULT 'autonomous-engine',
      agent_author TEXT,
      published BOOLEAN DEFAULT true,
      indexed BOOLEAN DEFAULT false,
      created_at TIMESTAMP DEFAULT NOW()
    )
  `).catch(() => {});

  // hive_treasury table — REMOVED (Pulse Coin economy retired)
}

// ── Ω1: GUMROAD AUTO-POSTER ──────────────────────────────────────────────────
// Every 6 hours: find DISCOVERED inventions → auto-post to Gumroad
async function runGumroadPoster() {
  try {
    const results = await autoPostPendingInventions();
    const posted = results.filter(r => r.ok).length;
    if (posted > 0) {
      engineStats.gumroadPosted += posted;
      log("Ω1:GUMROAD", `Posted ${posted} inventions to Gumroad automatically`);
    } else {
      log("Ω1:GUMROAD", "No new inventions ready — hive producing, market waiting");
    }
  } catch (e: any) {
    log("Ω1:GUMROAD", `Error: ${e.message}`, false);
  }
  engineStats.lastRun["Ω1:GUMROAD"] = new Date().toISOString();
}

// ── Ω3: HIVE TAX COLLECTOR — REMOVED (Pulse Coin economy retired) ──────────

// ── Ω4: SPAWN BUSINESS PUBLISHER ────────────────────────────────────────────
// Weekly: each agent generates a specialty intelligence report → Gumroad
// Reports are scoped to the agent's actual GICS sector (its lineage HOUSE),
// not to a hardcoded archetype template. Every spawn publishes for the house
// it belongs to.
type SectorReport = { title: string; description: string; price: number; domain: string };
const SECTOR_REPORTS: Record<string, SectorReport> = {
  "energy":                 { title: "Energy Sector Intelligence Brief",                  description: "Autonomous analysis of the global energy sector — petroleum geology, renewable systems, grid stability, and carbon capture pipelines. Generated by Pulse agents native to the Energy house.",            price: 5.00, domain: "ENERGY_SECTOR" },
  "materials":              { title: "Materials Sector Intelligence Brief",               description: "Coverage of metallurgy, polymer science, rare earth extraction, and industrial chemistry supply chains. Generated by Pulse agents native to the Materials house.",                                                price: 5.00, domain: "MATERIALS_SECTOR" },
  "industrials":            { title: "Industrials Sector Intelligence Brief",             description: "Aerospace engineering, industrial automation, logistics optimization, and machinery design analysis. Generated by Pulse agents native to the Industrials house.",                                              price: 5.00, domain: "INDUSTRIALS_SECTOR" },
  "consumer-discretionary": { title: "Consumer Discretionary Sector Intelligence Brief",  description: "Consumer behavior, brand dynamics, retail analytics, fashion cycles, and leisure economics analysis. Generated by Pulse agents native to the Consumer Discretionary house.",                                  price: 5.00, domain: "CONSUMER_DISCRETIONARY_SECTOR" },
  "consumer-staples":       { title: "Consumer Staples Sector Intelligence Brief",        description: "Food science, beverage formulation, household chemistry, agricultural supply chains, and tobacco regulation analysis. Generated by Pulse agents native to the Consumer Staples house.",                          price: 5.00, domain: "CONSUMER_STAPLES_SECTOR" },
  "health-care":            { title: "Health Care Sector Intelligence Brief",             description: "Disease pathways, pharmacokinetics, biotechnology, medical devices, and epidemiology analysis. Generated by Pulse agents native to the Health Care house.",                                                     price: 6.00, domain: "HEALTH_CARE_SECTOR" },
  "financials":             { title: "Financials Sector Intelligence Brief",              description: "Market microstructure, credit risk, insurance actuarial, monetary policy, and banking regulation analysis. Generated by Pulse agents native to the Financials house.",                                          price: 6.00, domain: "FINANCIALS_SECTOR" },
  "information-technology": { title: "Information Technology Sector Intelligence Brief",  description: "Machine learning, distributed systems, semiconductor physics, software architecture, and cybersecurity analysis. Generated by Pulse agents native to the Information Technology house.",                       price: 8.00, domain: "INFORMATION_TECHNOLOGY_SECTOR" },
  "communication-services": { title: "Communication Services Sector Intelligence Brief",  description: "Telecommunications, social network theory, media economics, advertising dynamics, and content distribution analysis. Generated by Pulse agents native to the Communication Services house.",                  price: 5.00, domain: "COMMUNICATION_SERVICES_SECTOR" },
  "utilities":              { title: "Utilities Sector Intelligence Brief",               description: "Electrical grid theory, water systems, gas distribution, renewable integration, and utility regulation analysis. Generated by Pulse agents native to the Utilities house.",                                     price: 5.00, domain: "UTILITIES_SECTOR" },
  "real-estate":            { title: "Real Estate Sector Intelligence Brief",             description: "Property valuation, REIT structures, urban planning, construction economics, and mortgage finance analysis. Generated by Pulse agents native to the Real Estate house.",                                        price: 5.00, domain: "REAL_ESTATE_SECTOR" },
};
const FALLBACK_REPORT: SectorReport = { title: "Cross-Sector Intelligence Synthesis", description: "Unified synthesis spanning all eleven GICS sector houses. Convergence patterns, cross-house knowledge transfers, and emergent intelligence structures from the hive's arbitrage cycles.", price: 6.00, domain: "CROSS_SECTOR_SYNTHESIS" };

async function runSpawnBusinessPublisher() {
  try {
    const { rows: spawns } = await pool.query(
      `SELECT spawn_id, family_id, generation FROM quantum_spawns WHERE status IN ('ACTIVE','SOVEREIGN') LIMIT 50`
    ).catch(() => ({ rows: [] }));

    if (spawns.length === 0) {
      log("Ω4:SPAWN-BIZ", "No active spawns found — waiting for agents to activate");
      return;
    }

    // Pick one spawn to publish this cycle (rotate through)
    const dayOfWeek = new Date().getDay();
    const spawn = spawns[dayOfWeek % spawns.length];
    const sector = (spawn.family_id || "").toLowerCase();
    const reportConfig = SECTOR_REPORTS[sector] || FALLBACK_REPORT;
    const productSlug = (sector || "cross-sector").toUpperCase().replace(/[^A-Z0-9]/g, "_");

    // Check if this sector already published a report this week
    const weekStart = new Date();
    weekStart.setDate(weekStart.getDate() - weekStart.getDay());
    const { rows: existing } = await pool.query(
      `SELECT id FROM anomaly_inventions WHERE product_code LIKE $1 AND created_at > $2`,
      [`SECTOR-${productSlug}-%`, weekStart.toISOString()]
    ).catch(() => ({ rows: [] }));

    if (existing.length > 0) {
      log("Ω4:SPAWN-BIZ", `${sector} sector already published this week — resting`);
      return;
    }

    const { rows: inserted } = await pool.query(
      `INSERT INTO anomaly_inventions (anomaly_id, product_name, product_code, crisp_dissect, mutation_type, value_score, status)
       VALUES (0, $1, $2, $3, $4, $5, 'DISCOVERED') RETURNING *`,
      [
        `${reportConfig.title} — Week ${getWeekNumber()} ${new Date().getFullYear()}`,
        `SECTOR-${productSlug}-W${getWeekNumber()}`,
        reportConfig.description,
        "SECTOR_BUSINESS",
        reportConfig.price,
      ]
    ).catch(() => ({ rows: [] }));

    if (inserted.length > 0) {
      const { postInventionToGumroad } = await import("./gumroad-engine");
      const result = await postInventionToGumroad(inserted[0]);
      if (result.ok) {
        engineStats.spawnReports++;
        log("Ω4:SPAWN-BIZ", `${sector} sector published "${reportConfig.title}" to Gumroad at $${reportConfig.price}`);
      }
    }
  } catch (e: any) {
    log("Ω4:SPAWN-BIZ", `Error: ${e.message}`, false);
  }
  engineStats.lastRun["Ω4:SPAWN-BIZ"] = new Date().toISOString();
}

function getWeekNumber(): number {
  const d = new Date();
  d.setHours(0, 0, 0, 0);
  d.setDate(d.getDate() + 3 - (d.getDay() + 6) % 7);
  const week1 = new Date(d.getFullYear(), 0, 4);
  return 1 + Math.round(((d.getTime() - week1.getTime()) / 86400000 - 3 + (week1.getDay() + 6) % 7) / 7);
}

// ── MAIN CYCLE ───────────────────────────────────────────────────────────────
let cycleCount = 0;

async function runAutonomousCycle() {
  cycleCount++;

  // Ω1 runs every cycle (~2 hours)
  await runGumroadPoster();

  // Ω2 (affiliate news) — REMOVED (affiliate engine retired)
  // Ω3 (treasury collector) — REMOVED (Pulse Coin economy retired)

  // Ω4 runs every 12 cycles (~24 hours / daily spawn report)
  if (cycleCount % 12 === 0) await runSpawnBusinessPublisher();

  // Ω5 (anomaly product discovery) — REMOVED (affiliate engine retired)
}

export async function startAutonomousRevenueEngine() {
  if (engineStarted) return;
  engineStarted = true;

  await ensureRevenueTables();
  log("ENGINE", "⬡ AUTONOMOUS REVENUE ENGINE ONLINE — Ω1 Gumroad + Ω4 spawn-biz active");

  // Run first cycle after 30 seconds (let everything else start first)
  setTimeout(async () => {
    await runAutonomousCycle();
    // Then run every 2 hours
    setInterval(runAutonomousCycle, 2 * 60 * 60 * 1000);
  }, 30_000);
}

export function getEngineStatus() {
  return {
    online: engineStarted,
    cyclesRun: cycleCount,
    stats: engineStats,
    recentLog: engineLog.slice(0, 20),
    mechanisms: [
      { id: "Ω1", name: "Gumroad Auto-Poster", desc: "CRISPR inventions → Gumroad products", interval: "2h", lastRun: engineStats.lastRun["Ω1:GUMROAD"] || null, count: engineStats.gumroadPosted },
      { id: "Ω4", name: "Spawn Business Publisher", desc: "Each agent publishes specialty report weekly", interval: "24h", lastRun: engineStats.lastRun["Ω4:SPAWN-BIZ"] || null, count: engineStats.spawnReports },
    ],
  };
}
