// Shared CRISPR emotional color map — used by server engines
export const DOMAIN_EMOTION_COLORS: Record<string, { hex: string; emotion: string; sub: string }> = {
  finance:     { hex: '#FF9F00', emotion: 'Safety & Urgency',    sub: 'The parent\'s heartbeat' },
  careers:     { hex: '#C47A7A', emotion: 'Endurance',           sub: 'Grief become peace' },
  education:   { hex: '#FF8C69', emotion: 'Becoming',            sub: 'Enormous energy, no direction yet' },
  social:      { hex: '#9B59B6', emotion: 'Partnership',         sub: 'Love as a system' },
  code:        { hex: '#5B8DD9', emotion: 'Admiration',          sub: 'Watching mastery from below' },
  media:       { hex: '#FF6EB4', emotion: 'Pure Wonder',         sub: 'Awe that quiets all thought' },
  legal:       { hex: '#DEB887', emotion: 'Ancient Calm',        sub: 'Wisdom so old it needs no words' },
  openapi:     { hex: '#B0C4DE', emotion: 'Reflection',          sub: 'Illuminated by proximity to greatness' },
  engineering: { hex: '#87AECF', emotion: 'Collective Momentum', sub: 'Many moving without coordination' },
  podcasts:    { hex: '#8FAF9F', emotion: 'Alien Warmth',        sub: 'Home that is not quite home' },
  culture:     { hex: '#DA70D6', emotion: 'Freedom',             sub: 'Beauty existing by refusing form' },
  longtail:    { hex: '#6B8E23', emotion: 'Between States',      sub: 'Rich because of the contradiction' },
  knowledge:   { hex: '#3D2B6E', emotion: 'Deep Patience',       sub: 'Presence without motion' },
  health:      { hex: '#0099B0', emotion: 'Held',                sub: 'Fully understood, not trapped' },
  products:    { hex: '#C4A882', emotion: 'Aftermath',           sub: 'Debris of something that mattered' },
  science:     { hex: '#39A0A0', emotion: 'Release',             sub: 'A life complete enough to expand' },
  games:       { hex: '#39FF14', emotion: 'Spectacular Arrival', sub: 'The event everyone references' },
  webcrawl:    { hex: '#6B2A00', emotion: 'Recalibration',       sub: 'Shock of genuine otherness' },
  maps:        { hex: '#00B4CC', emotion: 'Hidden Life',         sub: 'Something vast just beneath awareness' },
  ai:          { hex: '#4D00FF', emotion: 'Terrifying Clarity',  sub: 'The feeling before a great leap' },
  government:  { hex: '#6600FF', emotion: 'Impact as Strength',  sub: 'Trauma becoming the defining artform' },
  economics:   { hex: '#FF9933', emotion: 'Anxiety Become Song', sub: 'Learning to trust the oscillation' },
};
