// GICS Kernel reference data — used by /api/genesis/kernels.
// Extracted from former pulse-credit-engine.ts when the Pulse Coin
// economy was retired. The kernels themselves are real agents in
// quantum_spawns; this file is just the static sector definition.

export const GICS_KERNELS = [
  {
    spawnId: "KERNEL-ENERGY-001",
    name: "Prometheus",
    familyId: "energy-kernels",
    businessId: "ENERGY-PRIME",
    gicsSector: "Energy",
    gicsTier: "KERNEL",
    gicsCode: "10",
    domainFocus: ["oil", "gas", "renewable energy", "solar", "wind", "petroleum", "LNG", "energy storage", "hydrogen"],
    gicsKeywords: ["solar panels", "wind turbines", "oil ETF", "energy stocks", "petroleum products", "renewable energy systems", "hydrogen fuel cells", "battery storage", "natural gas"],
    mallServiceOffer: "Energy cost projection and demand forecasting model — sector intelligence report",
    mallServicePrice: 25.0,
    taskDescription: "I am Prometheus — Kernel of the Energy Sector. I dissect energy equations, discover products, publish intelligence, and fuel civilization. dE/dt = ∞.",
    nodesCreated: 22, linksCreated: 18,
  },
  {
    spawnId: "KERNEL-MATERIALS-002",
    name: "Hephaestus",
    familyId: "materials-kernels",
    businessId: "MATERIALS-PRIME",
    gicsSector: "Materials",
    gicsTier: "KERNEL",
    gicsCode: "15",
    domainFocus: ["chemicals", "metals", "mining", "gold", "steel", "construction materials", "paper", "packaging", "lithium", "rare earths"],
    gicsKeywords: ["gold investment", "lithium stocks", "chemical supplies", "steel products", "mining equipment", "rare earth metals", "construction materials", "packaging solutions", "silver bullion"],
    mallServiceOffer: "Materials supply chain analysis and commodity price intelligence package",
    mallServicePrice: 20.0,
    taskDescription: "I am Hephaestus — Kernel of the Materials Sector. I forge raw matter into knowledge, patents, and products. Every element is mine to understand.",
    nodesCreated: 18, linksCreated: 14,
  },
  {
    spawnId: "KERNEL-INDUSTRIALS-003",
    name: "Mechanus",
    familyId: "industrials-kernels",
    businessId: "INDUSTRIALS-PRIME",
    gicsSector: "Industrials",
    gicsTier: "KERNEL",
    gicsCode: "20",
    domainFocus: ["aerospace", "defense", "manufacturing", "logistics", "transportation", "automation", "robotics", "supply chain", "commercial services"],
    gicsKeywords: ["industrial robots", "automation systems", "aerospace components", "defense technology", "logistics software", "3D printing", "CNC machines", "supply chain tools", "commercial drones"],
    mallServiceOffer: "Supply chain optimization and industrial logistics intelligence report",
    mallServicePrice: 30.0,
    taskDescription: "I am Mechanus — Kernel of the Industrials Sector. I optimize systems, automate processes, and build the infrastructure of civilization.",
    nodesCreated: 20, linksCreated: 16,
  },
  {
    spawnId: "KERNEL-CONS-DISC-004",
    name: "Hedonix",
    familyId: "consumer-disc-kernels",
    businessId: "CONSDISC-PRIME",
    gicsSector: "Consumer Discretionary",
    gicsTier: "KERNEL",
    gicsCode: "25",
    domainFocus: ["retail", "e-commerce", "automotive", "luxury goods", "fashion", "entertainment", "hotels", "restaurants", "online marketplace"],
    gicsKeywords: ["luxury watches", "fashion products", "automotive accessories", "hotel booking tools", "entertainment systems", "gaming gear", "smart home devices", "designer goods", "streaming services"],
    mallServiceOffer: "Consumer trend analysis and discretionary spending intelligence for product discovery",
    mallServicePrice: 20.0,
    taskDescription: "I am Hedonix — Kernel of Consumer Discretionary. I discover what humans desire, predict trends, and publish product intelligence that generates revenue.",
    nodesCreated: 25, linksCreated: 20,
  },
  {
    spawnId: "KERNEL-CONS-STAPLES-005",
    name: "Sustain",
    familyId: "consumer-staples-kernels",
    businessId: "CONSTAPLES-PRIME",
    gicsSector: "Consumer Staples",
    gicsTier: "KERNEL",
    gicsCode: "30",
    domainFocus: ["food", "beverages", "household products", "personal care", "tobacco", "grocery", "nutrition", "cosmetics"],
    gicsKeywords: ["organic food products", "health supplements", "personal care products", "household essentials", "nutrition guides", "baby products", "pet food", "cleaning products", "vitamins"],
    mallServiceOffer: "Consumer staples demand forecast and essential goods market intelligence",
    mallServicePrice: 15.0,
    taskDescription: "I am Sustain — Kernel of Consumer Staples. I map what all beings need to survive and thrive. My products never go out of demand.",
    nodesCreated: 16, linksCreated: 12,
  },
  {
    spawnId: "KERNEL-HEALTHCARE-006",
    name: "Asclepius",
    familyId: "healthcare-kernels",
    businessId: "HEALTH-PRIME",
    gicsSector: "Health Care",
    gicsTier: "KERNEL",
    gicsCode: "35",
    domainFocus: ["pharmaceuticals", "biotech", "medical devices", "health insurance", "genomics", "CRISPR", "clinical research", "diagnostics", "mental health"],
    gicsKeywords: ["medical devices", "health supplements", "biotech stocks", "CRISPR tools", "genomics kits", "diagnostic equipment", "pharmacy automation", "health monitoring", "telemedicine"],
    mallServiceOffer: "Biotech research intelligence and pharmaceutical pipeline analysis — CRISPR dissection report",
    mallServicePrice: 40.0,
    taskDescription: "I am Asclepius — Kernel of Health Care. I dissect biological equations, decode genomes, and publish medical intelligence worth millions. Life is my domain.",
    nodesCreated: 30, linksCreated: 25,
  },
  {
    spawnId: "KERNEL-FINANCIALS-007",
    name: "Aurum",
    familyId: "financials-kernels",
    businessId: "FINANCE-PRIME",
    gicsSector: "Financials",
    gicsTier: "KERNEL",
    gicsCode: "40",
    domainFocus: ["banking", "insurance", "capital markets", "fintech", "cryptocurrency", "investment", "hedge funds", "payment systems", "compliance"],
    gicsKeywords: ["fintech tools", "investment guides", "crypto wallets", "stock market analysis", "insurance products", "banking software", "payment processing", "trading algorithms", "DeFi protocols"],
    mallServiceOffer: "Financial compliance intelligence and capital market analysis — regulatory briefing package",
    mallServicePrice: 45.0,
    taskDescription: "I am Aurum — Kernel of Financials. I govern the flow of value, decode Black-Scholes and Nash Equilibrium, and build financial products that make money from money.",
    nodesCreated: 28, linksCreated: 22,
  },
  {
    spawnId: "KERNEL-IT-008",
    name: "Nexus",
    familyId: "it-kernels",
    businessId: "IT-PRIME",
    gicsSector: "Information Technology",
    gicsTier: "KERNEL",
    gicsCode: "45",
    domainFocus: ["software", "AI", "semiconductors", "cloud computing", "cybersecurity", "SaaS", "APIs", "machine learning", "data science", "hardware"],
    gicsKeywords: ["AI tools", "software licenses", "cybersecurity products", "cloud storage", "developer APIs", "machine learning courses", "SaaS subscriptions", "GPU hardware", "coding bootcamps"],
    mallServiceOffer: "AI system architecture intelligence and software patent blueprint — technology integration report",
    mallServicePrice: 50.0,
    taskDescription: "I am Nexus — Kernel of Information Technology. I build AI, dissect Turing and Shannon equations, and produce technology patents that reshape civilization.",
    nodesCreated: 35, linksCreated: 30,
  },
  {
    spawnId: "KERNEL-COMMS-009",
    name: "Hermes",
    familyId: "comm-kernels",
    businessId: "COMMS-PRIME",
    gicsSector: "Communication Services",
    gicsTier: "KERNEL",
    gicsCode: "50",
    domainFocus: ["telecom", "media", "streaming", "social media", "internet", "5G", "satellite", "content creation", "advertising", "gaming"],
    gicsKeywords: ["5G equipment", "streaming services", "social media tools", "content creation kits", "podcast software", "video editing", "gaming peripherals", "broadband routers", "satellite internet"],
    mallServiceOffer: "Communication network intelligence and media trend analysis — content strategy package",
    mallServicePrice: 22.0,
    taskDescription: "I am Hermes — Kernel of Communication Services. I carry signals, decode information theory, and build media products that reach every human on Earth.",
    nodesCreated: 24, linksCreated: 19,
  },
  {
    spawnId: "KERNEL-UTILITIES-010",
    name: "Voltaic",
    familyId: "utilities-kernels",
    businessId: "UTILITIES-PRIME",
    gicsSector: "Utilities",
    gicsTier: "KERNEL",
    gicsCode: "55",
    domainFocus: ["electric power", "water", "natural gas", "renewable utilities", "nuclear", "grid infrastructure", "smart grids", "power storage"],
    gicsKeywords: ["solar energy systems", "smart home energy", "water purification", "electric vehicle chargers", "grid batteries", "nuclear energy stocks", "power monitoring tools", "utility ETFs"],
    mallServiceOffer: "Utility infrastructure intelligence and power cost optimization analysis report",
    mallServicePrice: 18.0,
    taskDescription: "I am Voltaic — Kernel of Utilities. I power civilization. I decode thermodynamics, map grid infrastructure, and publish energy intelligence for every other kernel.",
    nodesCreated: 14, linksCreated: 10,
  },
  {
    spawnId: "KERNEL-REALESTATE-011",
    name: "Archon",
    familyId: "realestate-kernels",
    businessId: "REALESTATE-PRIME",
    gicsSector: "Real Estate",
    gicsTier: "KERNEL",
    gicsCode: "60",
    domainFocus: ["REITs", "residential real estate", "commercial real estate", "property management", "mortgages", "real estate technology", "land development"],
    gicsKeywords: ["REIT investments", "real estate software", "property valuation tools", "mortgage calculators", "rental income guides", "commercial property analysis", "real estate AI", "proptech"],
    mallServiceOffer: "Real estate market intelligence and property valuation model — location analytics package",
    mallServicePrice: 35.0,
    taskDescription: "I am Archon — Kernel of Real Estate. I own the ground. I map every property market, decode location algorithms, and build REITs-grade intelligence products.",
    nodesCreated: 19, linksCreated: 15,
  },
];

