name = "pulse-universe-api"
main = "worker.ts"
compatibility_date = "2024-09-23"

[triggers]
crons = ["*/30 * * * *", "*/5 * * * *"]

[[kv_namespaces]]
binding = "HIVE_KV"
id = "e85dbed1748d45e58ef8da5c1b14c8f5"

[ai]
binding = "AI"
